services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - friend-svc
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
  member-svc:
    container_name: member-svc
    depends_on:
      - mydb
    ports:
      - 8080:8080
    networks:
      - ysg
    environment:
      - MARIADB_DB_HOST=mydb
      - MARIADB_DB_PORT=3306
      - MARIADB_DB_USER=root
      - MARIADB_DB_PASSWORD=1149
      - JWT_SECRET=dbstmdrnjsdmlxptmxmehzjtjqjqlalfzlzhem
      - JWT_ACC=30
      - JWT_REF=3
      - ALLOW_ORIGIN=http://localhost:3000
    image: yoonseungkwon/member-api:latest
  friend-svc:
    container_name: friend-svc
    depends_on:
      - mydb
    ports:
      - 8081:8080
    networks:
      - ysg
    environment:
      - MARIADB_DB_HOST=mydb
      - MARIADB_DB_PORT=3306
      - MARIADB_DB_USER=root
      - MARIADB_DB_PASSWORD=1149
      - JWT_SECRET=dbstmdrnjsdmlxptmxmehzjtjqjqlalfzlzhem
      - JWT_ACC=30
      - JWT_REF=3
      - ALLOW_ORIGIN=http://localhost:3000
      - SVC_MEMBER=member-svc
      - PORT_MEMBER=8080
    image: yoonseungkwon/friend-api:latest
  pin-svc:
    container_name: pin-svc
    depends_on:
      - friend-svc
    ports:
      - 8082:8080
    networks:
      - ysg
    environment:
      - MARIADB_DB_HOST=mydb
      - MARIADB_DB_PORT=3306
      - MARIADB_DB_USER=root
      - MARIADB_DB_PASSWORD=1149
      - JWT_SECRET=dbstmdrnjsdmlxptmxmehzjtjqjqlalfzlzhem
      - JWT_ACC=30
      - JWT_REF=3
      - ALLOW_ORIGIN=http://localhost:3000
    image: yoonseungkwon/pin-api:latest
  mydb:
    image: mariadb
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: 1149
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ysg

volumes:
  database:

networks:
  ysg:
